# Generated by Django 2.1.2 on 2018-10-16 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chisme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=100)),
                ('fecha_de_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
